spring.application.name=app

spring.datasource.url=jdbc:mariadb://192.168.3.103:3306/notifica
spring.datasource.username=backsql
#spring.datasource.username=neko
spring.datasource.password=88224646ba
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# Porta do Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8081/realms/Notifica
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8081/realms/Notifica/protocol/openid-connect/certs
    
# Configurações do Keycloak
keycloak.auth-server-url=http://keycloak:8081
keycloak.realm=Notifica
keycloak.resource=springboot-client
keycloak.credentials.secret=WgR0tQniN2zHaY9iC0BVHfJOnAFbBeJg
keycloak.public-client=false
keycloak.bearer-only=true
keycloak.ssl-required=none

# Para o UsuarioService novo
keycloak.client-id=${keycloak.resource}
keycloak.client-secret=${keycloak.credentials.secret}