# Dockerfile-notifica
FROM alpine:latest

# 1) Instala Nginx
RUN apk update
RUN apk add nginx
RUN apk add openssl
RUN apk add nano

EXPOSE 80 443

# 8) Comando de inicializa  o
CMD ["sh", "-c", "chmod -R 775 /opt/frontend-unifit && nginx -g 'daemon off;'"]
