# → /etc/nginx/http.d/reverse-proxy.conf ou /etc/nginx/http.d/default.conf
# → redireciona todo HTTP para HTTPS
server {
    listen 80;                # ipv4
    listen [::]:80;           # ipv6
    server_name notifica.net unifit;
    return 301 https://$host$request_uri;
}

# → Notifica via HTTPS
server {
    listen 443 ssl http2;
    server_name notifica.net;

    ssl_certificate     /opt/frontend-notifica/ssl_certificate/notifica.crt;
    ssl_certificate_key /opt/frontend-notifica/ssl_certificate/notifica.key;

    access_log  /opt/frontend-notifica/logs/reverse_access.log;
    error_log   /opt/frontend-notifica/logs/reverse_error.log;

    location / {
        proxy_pass         http://127.0.0.1:8080;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# → Unifit via HTTPS
server {
    listen 443 ssl http2;
    server_name unifit;

    ssl_certificate     /opt/frontend-unifit/ssl_certificate/unifit.crt;
    ssl_certificate_key /opt/frontend-unifit/ssl_certificate/unifit.key;

    access_log  /opt/frontend-unifit/logs/reverse_access.log;
    error_log   /opt/frontend-unifit/logs/reverse_error.log;

    location / {
        proxy_pass         http://127.0.0.1:8081;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
